# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler11
on: [pull_request]

jobs:
  prod-check:
    #if: ${{ github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    env:
      DAY_OF_WEEK: ${{ github.event.head_commit.message }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        env:
          message: ${{ github.event.head_commit.message }}
      - name: show commit message
        run : echo "$DAY_OF_WEEK $GITHUB_EVENT_NAME"
        
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          #################################
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '(^[0-9]+)'
          flags: 'gm'
          error: 'Your first line has to Start with a number.'
      
